SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `gdt`;
CREATE TABLE`gdt`(
id int(20) unsigned  NOT NULL AUTO_INCREMENT,
product_img int(20),
image text
PRIMARY KEY(`id`)
)ENGINE =InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET =utf8;