SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `images`;
CREATE TABLE`images`(
product_id int(20) unsigned  NOT NULL AUTO_INCREMENT,
id int(20),
color varchar(50) DEFAULT NULL,
image text,
PRIMARY KEY(`product_id`)
)ENGINE =InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET =utf8;
INSERT INTO `images` VALUES ('1','1',NULL,'../images/chanvay-05.jpg');
INSERT INTO `images` VALUES('2','2','charcoal green' ,'../images/vay-07.jpg');
INSERT INTO `images` VALUES('3','3','black','../images/vay-10.jpg');
INSERT INTO `images` VALUES('4','3','black','../images/vay-10.2.jpg');
INSERT INTO `images` VALUES('5','4',NUll,'../images/vay-08.jpg');
INSERT INTO `images` VALUES('6','4',NUll,'../images/vay-08.2.jpg');
INSERT INTO `images` VALUES('7','5',NUll,'../images/vay-09.jpg');
INSERT INTO `images` VALUES('8','6',NUll,'../images/chanvay-07.jpg');
INSERT INTO `images` VALUES('9','6',NUll,'../images/chanvay-07.1.jpg');
INSERT INTO `images` VALUES('10','6',NUll,'../images/chanvay-07.2.jpg');
INSERT INTO `images` VALUES('11','6',NUll,'../images/chanvay-07.3.jpg');
INSERT INTO `images` VALUES('12','7',NUll,'../images/jacket-06.jpg');
INSERT INTO `images` VALUES('13','7',NUll,'../images/jacket-06.1.jpg');
INSERT INTO `images` VALUES('14','8',NUll,'../images/quan-08.jpg');
INSERT INTO `images` VALUES('15','8',NUll,'../images/quan-08.2.jpg');
INSERT INTO `images` VALUES('16','9',NUll,'../images/jacket-09.jpg');
INSERT INTO `images` VALUES('17','9',NUll,'../images/jacket-09.1.jpg');
INSERT INTO `images` VALUES('18','10',NUll,'../images/chanvay-02.jpg');
INSERT INTO `images` VALUES('19','10',NUll,'../images/chanvay-03.jpg');
INSERT INTO `images` VALUES('20','11',NUll,'../images/blazer-01.jpg');
INSERT INTO `images` VALUES('21','11',NUll,'../images/blazer-01.3.jpg');
INSERT INTO `images` VALUES('22','12',NUll,'../images/vay-03.jpg');
INSERT INTO `images` VALUES('23','13','white','../images/ao-09.jpg');
INSERT INTO `images` VALUES('24','13','orange','../images/ao-09.1.jpg');
INSERT INTO `images` VALUES('25','14','beige','../images/vay-02.jpg');
INSERT INTO `images` VALUES('26','14','beige','../images/vay-02.3.jpg');
INSERT INTO `images` VALUES('27','15',NUll,'../images/jacket-07.jpg');
INSERT INTO `images` VALUES('28','15',NUll,'../images/jacket-07.1.jpg');
INSERT INTO `images` VALUES('29','16',NUll,'../images/quan-02.jpg');
INSERT INTO `images` VALUES('30','16',NUll,'../images/quan-02.1.jpg');
INSERT INTO `images` VALUES('31','17','black','../images/jacket-03.jpg');
INSERT INTO `images` VALUES('32','17','black','../images/jacket-03.1.jpg');
INSERT INTO `images` VALUES('33','18',NUll,'../images/ao-05.jpg');
INSERT INTO `images` VALUES('34','18',NUll,'../images/ao-05.1.jpg');
INSERT INTO `images` VALUES('35','19',NUll,'../images/jacket-04.jpg');
INSERT INTO `images` VALUES('36','19',NUll,'../images/jacket-04.1.jpg');
INSERT INTO `images` VALUES('37','20',NUll,'../images/jacket-05.jpg');
INSERT INTO `images` VALUES('38','21',NUll,'../images/quan-04.jpg');
INSERT INTO `images` VALUES('39','22','white','../images/vay-04.jpg');
INSERT INTO `images` VALUES('40','22','white','../images/vay-04.1.jpg');
INSERT INTO `images` VALUES('42','23','white','../images/blazer-02.jpg');
INSERT INTO `images` VALUES('43','23','white' ,'../images/blazer-02.2.jpg');
INSERT INTO `images` VALUES('44','24','grey' ,'../images/vay-05.jpg');
INSERT INTO `images` VALUES('45','25',null,'../images/jacket-08.jpg');
INSERT INTO `images` VALUES('46','26','brown','../images/vay-11.jpg');
INSERT INTO `images` VALUES('47','26',null,'../images/vay-11.2.jpg');
INSERT INTO `images` VALUES('48','27',null,'../images/tui-02.jpg');
INSERT INTO `images` VALUES('49','28','white','../images/boots-01.jpg');
INSERT INTO `images` VALUES('50','28','black','../images/boots-01.1.jpg');
INSERT INTO `images` VALUES('51','29',null,'../images/mu-01.jpg');
INSERT INTO `images` VALUES('52','30',null,'../images/mu-04.jpg');
INSERT INTO `images` VALUES('53','31','beige','../images/khan-01.jpg');
INSERT INTO `images` VALUES('54','31','white','../images/khan-01.2.jpg');
INSERT INTO `images` VALUES('55','32','black','../images/boots-02.jpg');
INSERT INTO `images` VALUES('56','33',null,'../images/mu-02.jpg');
INSERT INTO `images` VALUES('57','34','yellow','../images/tui-01.png');
INSERT INTO `images` VALUES('58','35',null,'../images/mu-03.jpg');
INSERT INTO `images` VALUES('59','4',null,'../images/vay-08.1.jpg');
INSERT INTO `images` VALUES('60','11',null,'../images/blazer-01.4.jpg');
INSERT INTO `images` VALUES('61','36',null,'../images/chanvay-01.jpg');
INSERT INTO `images` VALUES('62','36',null,'../images/chanvay-01.1.jpg');
INSERT INTO `images` VALUES('63','37','beige','../images/ao-02.jpg');
INSERT INTO `images` VALUES('64','37','beige','../images/ao-02.1.jpg');
INSERT INTO `images` VALUES('65','38',null,'../images/ao-06.jpg');
INSERT INTO `images` VALUES('66','38',null,'../images/ao-06.1.jpg');
INSERT INTO `images` VALUES('67','39','beige','../images/chanvay-04.jpg');
INSERT INTO `images` VALUES('68','40','purple pink','../images/ao-08.jpg');
INSERT INTO `images` VALUES('69','40','black','../images/ao-08.3.jpg');
INSERT INTO `images` VALUES('70','23','white','../images/blazer-02.1.jpg');
INSERT INTO `images` VALUES('71','3','black','../images/vay-10.1.jpg');
INSERT INTO `images` VALUES('72','41','beige','../images/jacket-02.jpg');
INSERT INTO `images` VALUES('73','41','beige','../images/jacket-01.jpg');
INSERT INTO `images` VALUES('74','42','brown','../images/ao-01.jpg');
INSERT INTO `images` VALUES('75','18',null,'../images/ao-05.2.jpg');
INSERT INTO `images` VALUES('76','43','white','..//images/ao-03.jpg');
INSERT INTO `images` VALUES('77','44',null,'../images/blazer-03.jpg');
INSERT INTO `images` VALUES('78','44',null,'../images/blazer-03.1.jpg');
INSERT INTO `images` VALUES('79','40','white','../images/ao-08.2.jpg');
INSERT INTO `images` VALUES('80','45','pink','../images/chanvay-07.jpg');
INSERT INTO `images` VALUES('81','45','pink','../images/chanvay-07.1.jpg');
INSERT INTO `images` VALUES('82','46','red','../images/chanvay-04.jpg');
INSERT INTO `images` VALUES('83','47',null,'../images/ao-07.jpg');
INSERT INTO `images` VALUES('84','48',null,'../images/jacket-10.jpg');
INSERT INTO `images` VALUES('85','48',null,'../images/jacket-10.1.jpg');
INSERT INTO `images` VALUES('86','48',null,'../images/jacket-10.2.jpg');
INSERT INTO `images` VALUES('87','48',null,'../images/jacket-10.3.jpg');
INSERT INTO `images` VALUES('88','9',NUll,'../images/jacket-09.1.jpg');
INSERT INTO `images` VALUES('89','19',NUll,'../images/jacket-04.2.jpg');
INSERT INTO `images` VALUES('90','49','grey','../images/ao-04.jpg');
INSERT INTO `images` VALUES('91','50',null,'../images/quan-05.jpg');
INSERT INTO `images` VALUES('92','8',NUll,'../images/quan-08.1.jpg');
INSERT INTO `images` VALUES('93','51',null,'../images/quan-06.jpg');
INSERT INTO `images` VALUES('94','52',null,'../images/quan-03.jpg');
INSERT INTO `images` VALUES('95','53',null,'../images/quan-07.jpg');
INSERT INTO `images` VALUES('96','54',null,'../images/quan-01.jpg');
INSERT INTO `images` VALUES('97','14','beige','../images/vay-02.2.jpg');
INSERT INTO `images` VALUES('98','14','purple','../images/vay-02.4.jpg');
INSERT INTO `images` VALUES('99','36',null,'../images/chanvay-01.2.jpg');
INSERT INTO `images` VALUES('100','26',null,'../images/vay-11.1.jpg');
INSERT INTO `images` VALUES('101','55','white','../images/vay-06.jpg');
INSERT INTO `images` VALUES('102','56',null,'../images/chanvay-06.jpg');
INSERT INTO `images` VALUES('103','57',null,'../images/vay-02.jpg');
INSERT INTO `images` VALUES('104','58',null,'../images/vay-07.jpg');
INSERT INTO `images` VALUES('105','59',null,'../images/vay-01.jpg');
INSERT INTO `images` VALUES('106','59',null,'../images/vay-01.1.jpg');
INSERT INTO `images` VALUES('107','59',null,'../images/vay-01.2.jpg');
INSERT INTO `images` VALUES('108','60',null,'../images/chanvay-05.jpg');
INSERT INTO `images` VALUES('109','61',null,'../images/chanvay-07.jpg');
INSERT INTO `images` VALUES('110','62',null,'../images/khan-03.jpg');
INSERT INTO `images` VALUES('111','62',null,'../images/khan-03.2.jpg');
INSERT INTO `images` VALUES('112','31','black','../images/khan-01.3.jpg');
INSERT INTO `images` VALUES('113','31','grey','../images/khan-01.1.jpg');
INSERT INTO `images` VALUES();
INSERT INTO `images` VALUES();
INSERT INTO `images` VALUES();